### ISSUE TITLE
Авторизация не работает.

### ISSUE THREAD

**Issue by olegatro** [atomoc/nodebb-plugin-sso-vk#1]
```
{"error":"invalid_request","error_description":"redirect_uri is incorrect, check application redirect uri in the settings page"}
```

Я уже часто видел такую ошибку, но в данном случаи не могу понять в чем проблема.

**Comment by atomoc** [comment]
Все поля настройки приложения, в разделе **Open API**, должны быть заполнены. В данном случае важно чтобы поле **Доверенный redirect URI** было заполнено примерно: `http://vashsajt.ru/auth/vkontakte/callback`
Можете несколько добавить, для тестирования, очень удобно.

**Comment by olegatro** [comment]
Да вроде все правильно написал
админка nodebb http://joxi.ru/GrqgaBZhL3aV2z
vk http://joxi.ru/v29lYyaFx86JmG

**Comment by atomoc** [comment]
Попробуй перейти по ссылке с `auth/vkontakte/callback`, какая ошибка возникнет

**Comment by olegatro** [comment]
unanimity.online/auth/vkontakte/callback
такая же о которой я писал вначале.

**Comment by olegatro** [comment]
Что то мне подсказывает с путями не то.

**Comment by atomoc** [comment]
Попробуй обратиться в тех- поддержку vk. Чувство что у них в списке не числится зона online.

**Comment by olegatro** [comment]
Ха, а вот будет интересный поворот, спасибо за совет, отпишусь как узнаю

**Comment by atomoc** [comment]
Попробуй ещё в папке плагина запустить `npm update`

**Comment by atomoc** [comment]
С трудом верится что в vk фильтруют зоны

**Comment by atomoc** [comment]
По крайней мере зоны рф в формате пьюникод принимаются на ура

**Comment by atomoc** [comment]
> Попробуй ещё в папке плагина запустить npm update

Проверил у себя, удалил папку с плагином и установил через nbbpm, никаких проблем, всё чётко.

**Comment by olegatro** [comment]
Еще я увидел, что урл с ошибкой содержит порт 4567. 
Ручками попробовал поправить и убрать цифры не помогло. А у вас через nginx nodebb стоит?

**Comment by atomoc** [comment]
Да, вот:

```
location /forum {
    proxy_pass http://127.0.0.1:4567/forum;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_redirect off;
    proxy_buffering   off;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}
```

В Apache:

```
ProxyPass /socket.io/1/websocket ws://127.0.0.1:4567/socket.io/1/websocket
ProxyPassReverse /socket.io/1/websocket ws://127.0.0.1:4567/socket.io/1/websocket

ProxyPass /forum http://127.0.0.1:4567/forum
ProxyPassReverse /forum http://127.0.0.1:4567/forum
```

**Comment by atomoc** [comment]
config.json:

```
{
    "url": "http://four.two.ru/forum",
    "secret": "ec1111d8-320a-4fdc-89cf-4f012345e491",
    "database": "redis",
    "redis": {
        "host": "127.0.0.1",
        "port": "6379",
        "database": "0"
    }
}
```

**Comment by olegatro** [comment]
Ура, Ваш последний коммент с конфигом всё решил, спасибо большое.
Дело в том что когда я устанавливал nodebb  и создавался config.json в нем в конце урла был указан порт. Незнаю почему, ручками я его туда точно не писал. Убрал порт из "url" и всё заработало.

И немного офтопа, у Вас возникали случаи резкой перезагрузки сервера? 
В первый раз когда я ставил nodebb год назад, я поставил редиску. После чего хостер ребутнул сервак, и вся инфа пропала. Редис на эту ситуацию плохо реагирует. Я не настраивал редиску на сохранение в файл, но после того раза, меня окутали сомнения об использовании редиски для хранения важной инфы с форума, поэтому на этот раз поставил на монге.
В документации видел, как они хотят внедрить использовать двух дб, одну для тем, постов, и т.д - монга, вторую для мелкой инфы - редиску.
Ну и у редиски есть минус, если у вас на форуме будет 1к человек, память быстро может заполнится, имхо.

**Comment by atomoc** [comment]
Здорово! Рад помочь!

Спасибо за инфу, даже не знаю что сейчас и делать, проект уже существует долго и много решалось именно под redis. Постоянно держу связь с тех- поддержкой хостинга, так как всё время падает, особенно с переходом на 0.8.x, но сейчас всё ок. Постоянные резервные копии базы должны решить проблему вероятного её безвозвратного опустошения. Посмотрим, может ничего больше не останется делать или разработчики придумают способ безболезненной миграции.

**Comment by olegatro** [comment]
Еще раз спасибо Вам за плагин, очень выручили.

**Comment by atomoc** [comment]
:)
